const translate = {
    "ru": {
        "mainpage__info":
            " AR вселенная – увлекательная игра и&nbsp;инструмент с&nbsp;помощью которого ты будешь находить и&nbsp;собирать разбросанные вокруг тебя настоящие деньги. ",
        "about__title": " О чем игра? ",
        "about__info": " <p> AR вселенная – увлекательная игра и&nbsp;инструмент с&nbsp;помощью которого ты будешь находить и&nbsp;собирать разбросанные вокруг тебя настоящие деньги, а&nbsp;так же иные ценности! </p> <p> Место приключений, квестов, общения с&nbsp;другими игроками, заработка. Место - где живут причудливые существа с&nbsp;искусственным интеллектом, новая форма разумной жизни. </p> ",
        "about__title2": " Цель игры ",
        "about__info2": " <p> AR вселенная – увлекательная игра и&nbsp;инструмент с&nbsp;помощью которого ты будешь находить и&nbsp;собирать разбросанные вокруг тебя настоящие деньги, а&nbsp;так же иные ценности! </p> <p> Место приключений, квестов, общения с&nbsp;другими игроками, заработка. Место - где живут причудливые существа с&nbsp;искусственным интеллектом, новая форма разумной жизни. </p> ",
        "steps__title": " Играй с друзьями ",
        "steps__text": " Место, где ты можешь играть вместе со&nbsp;своими друзьями ",
        "steps__title2": " Выполняй квесты ",
        "steps__text2": " Проходи захватывающие квесты по&nbsp;всему городу ",
        "steps__title3": " Получай награды ",
        "steps__text3": " Получай за&nbsp;это ценные награды и&nbsp;обменивай их на&nbsp;деньги ",
        "email__title": " Как начать играть? ",
        "email__info": " Наша игра находится в&nbsp;разработке. Подпишитесь на&nbsp;новости, чтобы попасть первым на&nbsp;открытие. ",
        "email-er": "Некорректно введена почта",
        "form__btntxt": "Отправить",
        "miticoin__title": " Основная валюта — MITICOIN ",
        "miticoin__info": " Расчётный инструмент метасети TitiMiti. Уникальная криптовалюта с&nbsp;механизмом стабильно-постоянного роста курса. Экономика проекта гарантирует, что цена MitiCoin никогда не&nbsp;будет ниже его бесконечно растущей капитализации. ",
        "miticoin__btntxt": "Подробнее",
        "phone__title": "Ищи сокровища",
        "phone__info": " <p> Расчётный инструмент метасети TitiMiti. Уникальная криптовалюта с&nbsp;механизмом стабильно-постоянного роста курса. Экономика проекта гарантирует, что цена MitiCoin никогда не&nbsp;будет ниже его бесконечно растущей капитализации. </p> <p> Экономика проекта гарантирует, что цена MitiCoin никогда не&nbsp;будет ниже его бесконечно растущей капитализации. </p> ",
        "picklocks__title": " Взламывай их&nbsp;отмычками ",
        "picklocks__info": " Для взлома сундука вам нужны отмычки.<br> Их можно купить в&nbsp;магазине или найти в&nbsp;открытом сундуке. ",
        "picklocks__btntxt": " Купить ",
        "awards__name": "Получай награды",
        "awards__info1": " Уникальная криптовалюта с&nbsp;механизмом стабильно-постоянного роста курса. ",
        "awards__info2": " Самый популярный стейбл коин, который обеспечивается запасами долларов США. ",
        "awards__title": "Бонусы от партнеров",
        "awards__info3": " Различные бонусы от&nbsp;наших партнеров.",
        "awards__info4": " Это NFT Miti-Coin, которые выдаются игрокам.",
        "awards__title2": "Предметы для игры ",
        "awards__info5": " Они помогут быстрее находить сокровища в Zoom Loupe.",
        "awards__info1": " Уникальная криптовалюта с&nbsp;механизмом стабильно-постоянного роста курса. ",
        "awards__info2": " Самый популярный стейбл коин, который обеспечивается запасами долларов США. ",
        "awards__title": "Бонусы от партнеров",
        "awards__info3": " Различные бонусы от&nbsp;наших партнеров. ",
        "awards__info4": " Это NFT Miti-Coin, которые выдаются игрокам.",
        "awards__title2": "Предметы для игры ",
        "awards__info5": " Они помогут быстрее находить сокровища в Zoom Loupe.",
        "equipments__title": " Система экипировки ",
        "equipments__text": " Есть различные виды экипировки ",
        "select-equipments__chose": "Очки",
        "e_m_1": "Модуль навигатора",
        "e_m_2": "Шапка",
        "e_m_3": "Очки",
        "e_m_4": "Цепочка",
        "e_m_5": "Куртка",
        "e_m_6": "Перчатки",
        "e_m_7": "Браслет",
        "e_m_8": "Штаны",
        "e_m_9": "Обувь",
        "eq_name_1": " Очки повышают характеристику “удача” ",
        "eq_info_1": " С помощью этого то-то-то.<br>Удача нужна для того-то того-то того-то. ",
        "eq_lvl_1_1": "Очки 1 уровня",
        "eq_boost_1_1": "Увеличивает удачу на&nbsp;<span>3%</span>",
        "eq_lvl_1_2": "Очки 2 уровня",
        "eq_boost_1_2": "Увеличивает удачу на&nbsp;<span>5%</span>",
        "eq_lvl_1_3": "Очки 3 уровня",
        "eq_boost_1_3": "Увеличивает удачу на&nbsp;<span>7%</span>",
        "eq_name_2": " Обувь - повышает характеристику “очки опыта” ",
        "eq_info_2": " С помощью этого то-то-то.<br>Удача нужна для того-то того-то того-то. ",
        "eq_lvl_2_1": "Обувь 1 уровня",
        "eq_boost_2_1": "Дает <span>100</span> едениц опыта",
        "eq_lvl_2_2": "Обувь 2 уровня",
        "eq_boost_2_2": "Дает <span>150</span> едениц опыта",
        "eq_lvl_2_3": "Обувь 3 уровня",
        "eq_boost_2_3": "Дает <span>200</span> едениц опыта",
        "eq_name_3": " Куртка - повышает характеристику “очки опыта” ",
        "eq_info_3": " С помощью этого то-то-то.<br>Удача нужна для того-то того-то того-то. ",
        "eq_lvl_3_1": "Куртка 1 уровня",
        "eq_boost_3_1": "Дает <span>150</span> едениц опыта",
        "eq_lvl_3_2": "Куртка 2 уровня",
        "eq_boost_3_2": "Дает <span>300</span> едениц опыта",
        "eq_lvl_3_3": "Куртка 3 уровня",
        "eq_boost_3_3": "Дает <span>600</span> едениц опыта",
        "eq_name_4": " Штаны - повышают характеристику “очки опыта”. ",
        "eq_info_4": " С помощью этого то-то-то.<br>Удача нужна для того-то того-то того-то. ",
        "eq_lvl_4_1": "Штаны 1 уровня",
        "eq_boost_4_1": "Дает <span>100</span> едениц опыта",
        "eq_lvl_4_2": "Штаны 2 уровня",
        "eq_boost_4_2": "Дает <span>200</span> едениц опыта",
        "eq_lvl_4_3": "Штаны 3 уровня",
        "eq_boost_4_3": "Дает <span>400</span> едениц опыта",
        "eq_name_5": " Штаны - повышают характеристику “очки опыта”. ",
        "eq_info_5": " С помощью этого то-то-то.<br>Удача нужна для того-то того-то того-то. ",
        "eq_lvl_5_1": "Перчатки 1 уровня",
        "eq_boost_5_1": "Увеличивает удачу на <span>3%</span>",
        "eq_lvl_5_2": "Перчатки 2 уровня",
        "eq_boost_5_2": "Увеличивает удачу на <span>7%</span>",
        "eq_lvl_5_3": "Перчатки 3 уровня",
        "eq_boost_5_3": "Увеличивает удачу на <span>10%</span>",
        "helpus__txt": " Помоги нам и получи за это бонусы ",
        "helpus__title": "Стань исследователем",
        "helpus__info": " У тебя будет возможность...<br> За это ты будешь получать...<br> И еще какое-то описание<br> ",
        "helpus__btntxt": "Подробнее",
    },
    "en": {
        "mainpage__info": "",
        "about__title": "",
        "about__info": "",
        "about__title2": "",
        "about__info2": "",
        "steps__title": "",
        "steps__text": "",
        "steps__title2": "",
        "steps__text2": "",
        "steps__title3": "",
        "steps__text3": "",
        "email__title": "",
        "email__info": "",
        "email-er": "",
        "form__btntxt": "",
        "miticoin__title": "",
        "miticoin__info": "",
        "miticoin__btntxt": "",
        "phone__title": "",
        "phone__info": "",
        "picklocks__title": "",
        "picklocks__info": "",
        "picklocks__btntxt": "",
        "awards__name": "",
        "awards__info1": "",
        "awards__info2": "",
        "awards__title": "",
        "awards__info3": "",
        "awards__info4": "",
        "awards__title2": "",
        "awards__info5": "",
        "awards__info1": "",
        "awards__info2": "",
        "awards__title": "",
        "awards__info3": "",
        "awards__info4": "",
        "awards__title2": "",
        "awards__info5": "",
        "equipments__title": "",
        "equipments__text": "",
        "select-equipments__chose": "",
        "e_m_1": "",
        "e_m_2": "",
        "e_m_3": "",
        "e_m_4": "",
        "e_m_5": "",
        "e_m_6": "",
        "e_m_7": "",
        "e_m_8": "",
        "e_m_9": "",
        "eq_name_1": "",
        "eq_info_1": "",
        "eq_lvl_1_1": "",
        "eq_boost_1_1": "",
        "eq_lvl_1_2": "",
        "eq_boost_1_2": "",
        "eq_lvl_1_3": "",
        "eq_boost_1_3": "",
        "eq_name_2": "",
        "eq_info_2": "",
        "eq_lvl_2_1": "",
        "eq_boost_2_1": "",
        "eq_lvl_2_2": "",
        "eq_boost_2_2": "",
        "eq_lvl_2_3": "",
        "eq_boost_2_3": "",
        "eq_name_3": "",
        "eq_info_3": "",
        "eq_lvl_3_1": "",
        "eq_boost_3_1": "",
        "eq_lvl_3_2": "",
        "eq_boost_3_2": "",
        "eq_lvl_3_3": "",
        "eq_boost_3_3": "",
        "eq_name_4": "",
        "eq_info_4": "",
        "eq_lvl_4_1": "",
        "eq_boost_4_1": "",
        "eq_lvl_4_2": "",
        "eq_boost_4_2": "",
        "eq_lvl_4_3": "",
        "eq_boost_4_3": "",
        "eq_name_5": "",
        "eq_info_5": "",
        "eq_lvl_5_1": "",
        "eq_boost_5_1": "",
        "eq_lvl_5_2": "",
        "eq_boost_5_2": "",
        "eq_lvl_5_3": "",
        "eq_boost_5_3": "",
        "helpus__txt": "",
        "helpus__title": "",
        "helpus__info": "",
        "helpus__btntxt": "",
    },
    "zh": {
        "mainpage__info": "",
        "about__title": "",
        "about__info": "",
        "about__title2": "",
        "about__info2": "",
        "steps__title": "",
        "steps__text": "",
        "steps__title2": "",
        "steps__text2": "",
        "steps__title3": "",
        "steps__text3": "",
        "email__title": "",
        "email__info": "",
        "email-er": "",
        "form__btntxt": "",
        "miticoin__title": "",
        "miticoin__info": "",
        "miticoin__btntxt": "",
        "phone__title": "",
        "phone__info": "",
        "picklocks__title": "",
        "picklocks__info": "",
        "picklocks__btntxt": "",
        "awards__name": "",
        "awards__info1": "",
        "awards__info2": "",
        "awards__title": "",
        "awards__info3": "",
        "awards__info4": "",
        "awards__title2": "",
        "awards__info5": "",
        "awards__info1": "",
        "awards__info2": "",
        "awards__title": "",
        "awards__info3": "",
        "awards__info4": "",
        "awards__title2": "",
        "awards__info5": "",
        "equipments__title": "",
        "equipments__text": "",
        "select-equipments__chose": "",
        "e_m_1": "",
        "e_m_2": "",
        "e_m_3": "",
        "e_m_4": "",
        "e_m_5": "",
        "e_m_6": "",
        "e_m_7": "",
        "e_m_8": "",
        "e_m_9": "",
        "eq_name_1": "",
        "eq_info_1": "",
        "eq_lvl_1_1": "",
        "eq_boost_1_1": "",
        "eq_lvl_1_2": "",
        "eq_boost_1_2": "",
        "eq_lvl_1_3": "",
        "eq_boost_1_3": "",
        "eq_name_2": "",
        "eq_info_2": "",
        "eq_lvl_2_1": "",
        "eq_boost_2_1": "",
        "eq_lvl_2_2": "",
        "eq_boost_2_2": "",
        "eq_lvl_2_3": "",
        "eq_boost_2_3": "",
        "eq_name_3": "",
        "eq_info_3": "",
        "eq_lvl_3_1": "",
        "eq_boost_3_1": "",
        "eq_lvl_3_2": "",
        "eq_boost_3_2": "",
        "eq_lvl_3_3": "",
        "eq_boost_3_3": "",
        "eq_name_4": "",
        "eq_info_4": "",
        "eq_lvl_4_1": "",
        "eq_boost_4_1": "",
        "eq_lvl_4_2": "",
        "eq_boost_4_2": "",
        "eq_lvl_4_3": "",
        "eq_boost_4_3": "",
        "eq_name_5": "",
        "eq_info_5": "",
        "eq_lvl_5_1": "",
        "eq_boost_5_1": "",
        "eq_lvl_5_2": "",
        "eq_boost_5_2": "",
        "eq_lvl_5_3": "",
        "eq_boost_5_3": "",
        "helpus__txt": "",
        "helpus__title": "",
        "helpus__info": "",
        "helpus__btntxt": "",
    }
}